#jinja2: variable_start_string:'${', variable_end_string:'}', trim_blocks: True
apiVersion: v1
kind: Secret
metadata:
  name: certs-admission-controller
  namespace: "admission-controller"
data:
  cert.pem: '${ADMISSION_CONTROLLER_SERVER_CERT}'
  key.pem: '${ADMISSION_CONTROLLER_SERVER_PRIV_KEY}'
